# UrrunBerri OS — Plymouth Boot Theme
# Openema SARL — Mathieu Cadi

Window.SetBackgroundTopColor(0.933, 0.949, 0.969);
Window.SetBackgroundBottomColor(0.933, 0.949, 0.969);

logo.image = Image("logo.png");
logo.image = logo.image.Scale(600, 600);
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
logo.sprite.SetY(Window.GetHeight() / 2 - logo.image.GetHeight() / 2);
logo.sprite.SetOpacity(1);
